config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:show, :index, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w[ chinese italian japanese french belgian ] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET all restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/id
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private
  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    # @review.restaurant = @restaurant
    @review.restaurant_id = @restaurant.id
    if @review.save
      redirect_to restaurant_path(@restaurant.id)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review)
          .permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Here are our restaurants 🍽</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.category %></td>
        <td><%= link_to 'See more ➡️', restaurant %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Restaurant', new_restaurant_path, class:"btn btn-primary" %>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant 🍽</h1>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit class:"btn btn-primary"%>
<% end %>
<%= link_to 'Back to all restaurants', restaurants_path, class:"btn btn-primary" %>

app/views/restaurants/show.html.erb
<div class="container">
  <h2>
    <%= @restaurant.name %>
  </h2>

  <h3>
    Where? 📍 <%= @restaurant.address %>
  </h3>

  <h3>
    Category? 🌍 <%= @restaurant.category %>
  </h3>

  <%= link_to 'Back to all restaurants', restaurants_path, class:"btn btn-primary" %>

  <h3> What do our customers think? Here are <%= @restaurant.name %>'s reviews 🕵🏻‍♂️</h3>

  <%= link_to 'Leave a Review', new_restaurant_review_path(@restaurant), class:"btn btn-primary" %>

  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <h3>Rating <%= review.rating %></h3>
        <p><%= review.content %></p>
      </li>
    <% end %>
  </ul>

</div>

app/views/reviews/new.html.erb
<h1>Leave a review! 🍽</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit class:"btn btn-primary"%>
<% end %>
<%= link_to 'Back to restaurant', restaurant_path(@restaurant), class:"btn btn-primary" %>